### PR TITLE
add findbyExamId feature

### PR DESCRIPTION
**Pull request by ZBDGIT**
add findbyExamId feature

### CODE REVIEW

**Review by treycrossley — APPROVED** [review]
assuming it passes tests, looks good to me!

**Comment by ZBDGIT** [comment]
wait a sec

**Comment by treycrossley** [comment]
HAHA ill wait

**Comment by ZBDGIT** [comment]
not sure the base the lastest one

**Comment by treycrossley** [comment]
i was LITERALLY about to click merge. Imma just message you on teams

**Comment by ZBDGIT** [comment]
not very sure

**Pull request merged**
